const criteria = [
    { nameCriteria: 'Paris', nameGallery: 'Paris', subCriteria: null },
    { nameCriteria: 'bâtiments administratifs', nameGallery: 'admin', subCriteria: null },
    { nameCriteria: 'quartiers pittoresques', nameGallery: 'neighborhood', subCriteria: null },
    {
        nameCriteria: 'arrondissements',
        nameGallery: 'districtsPhotos',
        subCriteria: [
            { nameCriteria: 'Ier', nameGallery: 'districtsPhotos[0]' },
            { nameCriteria: 'IIe', nameGallery: 'districtsPhotos[1]' },
            { nameCriteria: 'IIIe', nameGallery: 'districtsPhotos[2]' },
            { nameCriteria: 'IVe', nameGallery: 'districtsPhotos[3]' },
            { nameCriteria: 'Ve', nameGallery: 'districtsPhotos[4]' },
            { nameCriteria: 'VIe', nameGallery: 'districtsPhotos[5]' },
            { nameCriteria: 'VIIe', nameGallery: 'districtsPhotos[6]' },
            { nameCriteria: 'VIIIe', nameGallery: 'districtsPhotos[7]' },
            { nameCriteria: 'IXe', nameGallery: 'districtsPhotos[8]' },
            { nameCriteria: 'Xe', nameGallery: 'districtsPhotos[9]' },
            { nameCriteria: 'XIe', nameGallery: 'districtsPhotos[10]' },
            { nameCriteria: 'XIIe', nameGallery: 'districtsPhotos[11]' },
            { nameCriteria: 'XIIIe', nameGallery: 'districtsPhotos[12]' },
            { nameCriteria: 'XIVe', nameGallery: 'districtsPhotos[13]' },
            { nameCriteria: 'XVe', nameGallery: 'districtsPhotos[14]' },
            { nameCriteria: 'XVIe', nameGallery: 'districtsPhotos[15]' },
            { nameCriteria: 'XVIIe', nameGallery: 'districtsPhotos[16]' },
            { nameCriteria: 'XVIIIe', nameGallery: 'districtsPhotos[17]' },
            { nameCriteria: 'XIXe', nameGallery: 'districtsPhotos[18]' },
            { nameCriteria: 'XXe', nameGallery: 'districtsPhotos[19]' },
        ],
    },
    { nameCriteria: 'tour eiffel', nameGallery: 'tourEiffel', subCriteria: null },
    { nameCriteria: 'champs élysées', nameGallery: 'champsElysees', subCriteria: null },
    { nameCriteria: 'louvre', nameGallery: 'louvre', subCriteria: null },
    { nameCriteria: 'Arc de Triomphe', nameGallery: 'arcDeTriomphe', subCriteria: null },
    { nameCriteria: 'pont neuf', nameGallery: 'pontNeuf', subCriteria: null },
    { nameCriteria: 'centre Pompidou', nameGallery: 'centrePompidou', subCriteria: null },
    { nameCriteria: "musée d'Orsay", nameGallery: 'museeOrsay', subCriteria: null },
    { nameCriteria: 'montmartre', nameGallery: 'montmartre', subCriteria: null }
];

export default criteria;
