// galleryNames.js
export const GALLERY_NAMES = {
    PARIS: 'Paris',
    BUILDINGS: 'bâtiments administratifs',
    NEIGHBORHOODS: 'quartiers pittoresques',
    DISTRICTS: 'arrondissements',
    FIRST: 'Ier',
    SECOND: 'IIe',
    THIRD: 'IIIe',
    FOURTH: 'IVe',
    FITH: 'Ve',
    SIXTH: 'VIe',
    SEVENTH: 'VIIe',
    EIGHTH: 'VIIIe',
    NINTH: 'IXe',
    TENTH: 'Xe',
    ELEVENTH: 'XIe',
    TWELFTH: 'XIIe',
    THIRTEENTH: 'XIIIe',
    FOURTHEENTH: 'XIVe',
    FIFTEENTH: 'XVe',
    SIXTEENTH: 'XVIe',
    SEVENTEENTH: 'XVIIe',
    HEIGHTEENTH: 'XVIIIe',
    NINETEENTH: 'XIXe',
    TWEENTIETH: 'XXe',
    TOUR_EIFFEL: "tour eiffel",
    CHAMPS_ELYSEE: "champs élysées",
    LOUVRE: "louvre",
    ARC_DE_TRIOMPHE: "arc de triomphe",
    PONT_NEUF: "pont neuf",
    CENTRE_POMPIDOU: "centre Pompidou",
    MUSEE_DORSAY: "musée d'Orsay",
};
